export const ipcChannels = {
  snapshot: "threadleaf:snapshot",
  snapshotChanged: "threadleaf:snapshot-changed",
  settings: "threadleaf:settings",
  settingsChanged: "threadleaf:settings-changed",
  searchVault: "threadleaf:search-vault",
  loadVaultImage: "threadleaf:load-vault-image",
  setKeyBinding: "threadleaf:set-key-binding",
  resetKeyBindings: "threadleaf:reset-key-bindings",
  chooseVault: "threadleaf:choose-vault",
  openNote: "threadleaf:open-note",
  closeNote: "threadleaf:close-note",
  createNote: "threadleaf:create-note",
  saveNote: "threadleaf:save-note",
  runCommand: "threadleaf:run-command",
  reloadPlugin: "threadleaf:reload-plugin",
  unloadPlugin: "threadleaf:unload-plugin",
} as const;
