export const nativeMenuCommandIds = [
  "ui.command-palette",
  "settings.open-keybindings",
  "workspace.open-vault",
  "workspace.quick-switcher",
  "workspace.create-note",
  "workspace.open-daily-note",
  "workspace.open-file-recovery",
  "workspace.export-note-html",
  "workspace.toggle-note-bookmark",
  "workspace.toggle-tab-pin",
  "workspace.open-graph-view",
  "workspace.open-local-graph",
  "workspace.close-tab",
  "workspace.go-back",
  "workspace.go-forward",
  "workspace.split-right",
  "workspace.split-down",
  "workspace.move-tab-to-other-pane",
  "workspace.close-pane",
  "workspace.next-tab",
  "workspace.previous-tab",
  "workspace.focus-note-filter",
  "editor.insert-template",
  "editor.insert-current-date",
  "editor.insert-current-time",
  "editor.toggle-checkbox-status",
  "editor.toggle-reading-view",
  "editor.toggle-source-mode",
  "appearance.toggle-theme",
  "appearance.reload-custom-css",
  "support.export-bundle",
] as const;

export type NativeMenuCommandId = (typeof nativeMenuCommandIds)[number];
